/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.BloodLeukemia_Centre_Coordinator_Role;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.People.Donor;
import Magic.Design.*;
import Business.People.Patient;
import Magic.Design.MyJLabel;
import Business.People.PatientRequest;
import Magic.Design.MyJButton;
import Magic.Design.MyTableFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abhishekmathukiya
 */
public class PatientStatusJPanel extends javax.swing.JPanel {

    private EcoSystem system;
      private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    PatientStatusJPanel(EcoSystem system) {
        initComponents();
        this.system = system;
        tblPatient.getTableHeader().setDefaultRenderer(new MyTableFormat());
         lblPatientTable.getTableHeader().setDefaultRenderer(new MyTableFormat());
        populatePatientTable();
        populatePatientRequestsTable();
        
    }
    private void populatePatientTable(){
        DefaultTableModel dtm = (DefaultTableModel) tblPatient.getModel();
        
        dtm.setRowCount(0);
        
         for(Patient patient: system.getPatientDirectory().getPatientList())
         {            
            Object row[] = new Object[4];
            row[0]= patient;
            row[1]=patient.getName();
            row[2]=patient.getContact();
            row[3]=patient.getStatus();
              
            dtm.addRow(row);
         }
    }
    
     private void populatePatientRequestsTable(){
        DefaultTableModel dtm = (DefaultTableModel) lblPatientTable.getModel();
        
        dtm.setRowCount(0);
        
         for(PatientRequest patient: system.getPatientRequestDirectory().getPatientRequestList())
         {            
            Object row[] = new Object[4];
            row[0]= patient;
            row[1]=patient.getName();
            row[2]=patient.getContact();
            row[3]=patient.getStatus();
              
            dtm.addRow(row);
         }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPatientRequest = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatient = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblPatientStatus = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblPatientTable = new javax.swing.JTable();
        lblPatientTreatment = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setMinimumSize(new java.awt.Dimension(1100, 720));
        setPreferredSize(new java.awt.Dimension(1150, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPatientRequest.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblPatientRequest.setText("All Patient Requests");
        add(lblPatientRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, -1));

        tblPatient.setBackground(new java.awt.Color(153, 153, 153));
        tblPatient.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        tblPatient.setForeground(new java.awt.Color(255, 255, 255));
        tblPatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient ID", "Name", "Contact", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPatient.setFocusable(false);
        tblPatient.setGridColor(new java.awt.Color(0, 0, 0));
        tblPatient.setRowHeight(30);
        jScrollPane1.setViewportView(tblPatient);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 730, 190));

        btnDelete.setBackground(new java.awt.Color(102, 102, 102));
        btnDelete.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 610, 80, 30));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(926, 70));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        lblPatientStatus.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblPatientStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientStatus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPatientStatus.setText("                                                                         Patient's Status");
        jPanel3.add(lblPatientStatus);

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1800, -1));

        lblPatientTable.setBackground(new java.awt.Color(153, 153, 153));
        lblPatientTable.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblPatientTable.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient ID", "Name", "Contact", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        lblPatientTable.setFocusable(false);
        lblPatientTable.setGridColor(new java.awt.Color(0, 0, 0));
        lblPatientTable.setRowHeight(30);
        jScrollPane2.setViewportView(lblPatientTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 730, 210));

        lblPatientTreatment.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblPatientTreatment.setText("Patients In Need Of Cancer Treatment");
        add(lblPatientTreatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/BloodLeukemia_Centre_Coordinator_Role/cancerpatient copy.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, -150, 660, 960));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = lblPatientTable.getSelectedRow(); 
        PatientRequest dr = (PatientRequest) lblPatientTable.getValueAt(selectedRow, 0);

        system.getPatientRequestDirectory().removePatientRequest(dr);

        dB4OUtil.storeSystem(system);
        populatePatientRequestsTable();
        
        
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPatientRequest;
    private javax.swing.JLabel lblPatientStatus;
    private javax.swing.JTable lblPatientTable;
    private javax.swing.JLabel lblPatientTreatment;
    private javax.swing.JTable tblPatient;
    // End of variables declaration//GEN-END:variables
}
