/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AdministrativeRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Magic.Design.MyJLabel;
import Magic.Design.MyJTextField;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Magic.Design.MyJButton;
import Magic.Design.MyTableFormat;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *

 * @author abhishekmathukiya

 */
public class ManageEmployeeJPanel extends javax.swing.JPanel {

    private OrganizationDirectory organizationDir;
    private JPanel userProcessContainer;
    
    EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    
    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageEmployeeJPanel(JPanel userProcessContainer,OrganizationDirectory organizationDir, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organizationDir = organizationDir;
        this.system = system;
        
        tblOrganization.getTableHeader().setDefaultRenderer(new MyTableFormat());
        populateOrganizationComboBox();
        //populateOrganizationEmpComboBox();
        //populateTable();
        txtEnterpriseName.setText(enterprise.getName());
        
    }
     private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblOrganization.getModel();

        model.setRowCount(0);
        for (Organization o : organizationDir.getOrganizationList()) {
            for (Employee employee : o.getEmployeeDirectory().getEmployeeList()) {
                Object[] row = new Object[3];
                row[0] = o;
                row[1] = o.getRealName();
                row[2] = employee.getName();
                model.addRow(row);
            }

        }

    }
    public void populateOrganizationComboBox(){
        cmbOrganizationType.removeAllItems();
        
        for (Organization organization : organizationDir.getOrganizationList()){
            cmbOrganizationType.addItem(organization);
            
            
            
        }
    }
    
    public void populateOrganizationEmpComboBox(){
        cmbOrganizationName.removeAllItems();
        
        for (Organization organization : organizationDir.getOrganizationList()){
            cmbOrganizationName.addItem(organization.getRealName());
        }
    }

    private void populateTable(Organization organization){
        DefaultTableModel model = (DefaultTableModel) tblOrganization.getModel();
        
        model.setRowCount(0);
        
        for (Employee employee : organization.getEmployeeDirectory().getEmployeeList()){
            Object[] row = new Object[3];
            row[0] = organization;
            row[1] = organization.getRealName();
            row[2] = employee;
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseNameTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrganization = new javax.swing.JTable();
        lblEnterprise = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblManageEmployee = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblCreateEmployee = new javax.swing.JLabel();
        lblNameOfEmployee = new javax.swing.JLabel();
        nameSeparator = new javax.swing.JSeparator();
        lblTypeOfOrganization = new javax.swing.JLabel();
        cmbOrganizationType = new javax.swing.JComboBox();
        cmbOrganizationName = new javax.swing.JComboBox();
        lblNameOfOrganization = new javax.swing.JLabel();
        nameSeparator1 = new javax.swing.JSeparator();
        nameSeparator3 = new javax.swing.JSeparator();
        txtNameOfEmployee = new javax.swing.JTextField();
        btnCreateEmployee = new javax.swing.JButton();
        nameSeparator4 = new javax.swing.JSeparator();
        txtEnterpriseName = new javax.swing.JTextField();

        enterpriseNameTextField.setBackground(new java.awt.Color(55, 96, 128));
        enterpriseNameTextField.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        enterpriseNameTextField.setBorder(null);
        enterpriseNameTextField.setCaretColor(new java.awt.Color(30, 59, 92));
        enterpriseNameTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                enterpriseNameTextFieldFocusGained(evt);
            }
        });
        enterpriseNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseNameTextFieldActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblOrganization.setBackground(new java.awt.Color(153, 153, 153));
        tblOrganization.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 255, 204)));
        tblOrganization.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        tblOrganization.setForeground(new java.awt.Color(255, 255, 255));
        tblOrganization.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organization Type", "Organization Name", "Employee Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrganization.setGridColor(new java.awt.Color(0, 0, 0));
        tblOrganization.setRowHeight(30);
        tblOrganization.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tblOrganizationInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(tblOrganization);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 670, 220));

        lblEnterprise.setBackground(new java.awt.Color(0, 0, 0));
        lblEnterprise.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblEnterprise.setText("Enterprise:");
        add(lblEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, -1, -1));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(1550, 70));

        lblManageEmployee.setBackground(new java.awt.Color(255, 153, 153));
        lblManageEmployee.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblManageEmployee.setForeground(new java.awt.Color(255, 255, 255));
        lblManageEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblManageEmployee.setText("Manage Employee");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(lblManageEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(587, 587, 587))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(lblManageEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1680, -1));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 400));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setVerifyInputWhenFocusTarget(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCreateEmployee.setBackground(new java.awt.Color(0, 0, 0));
        lblCreateEmployee.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        lblCreateEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateEmployee.setText("Create Employee");
        jPanel2.add(lblCreateEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 233, 36));

        lblNameOfEmployee.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblNameOfEmployee.setText("Name of Employee");
        jPanel2.add(lblNameOfEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 180, 26));

        nameSeparator.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(nameSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 300, 10));

        lblTypeOfOrganization.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTypeOfOrganization.setText("Type of Organization");
        jPanel2.add(lblTypeOfOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 200, 26));

        cmbOrganizationType.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        cmbOrganizationType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbOrganizationTypeItemStateChanged(evt);
            }
        });
        cmbOrganizationType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbOrganizationTypeMouseClicked(evt);
            }
        });
        cmbOrganizationType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrganizationTypeActionPerformed(evt);
            }
        });
        jPanel2.add(cmbOrganizationType, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 210, 30));

        cmbOrganizationName.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jPanel2.add(cmbOrganizationName, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 210, 30));

        lblNameOfOrganization.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblNameOfOrganization.setText("Name of Organization");
        jPanel2.add(lblNameOfOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 220, 26));

        nameSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(nameSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, 300, -1));

        nameSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(nameSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 300, 10));

        txtNameOfEmployee.setBackground(new java.awt.Color(242, 242, 242));
        txtNameOfEmployee.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        txtNameOfEmployee.setBorder(null);
        jPanel2.add(txtNameOfEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 220, 30));

        btnCreateEmployee.setBackground(new java.awt.Color(153, 153, 153));
        btnCreateEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateEmployee.setText("Create Employee");
        btnCreateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateEmployeeActionPerformed(evt);
            }
        });
        jPanel2.add(btnCreateEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 100, 150, 40));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 1370, 270));

        nameSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        add(nameSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 480, 200, 20));

        txtEnterpriseName.setEditable(false);
        txtEnterpriseName.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        txtEnterpriseName.setBorder(null);
        add(txtEnterpriseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 200, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void cmbOrganizationTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrganizationTypeActionPerformed
        Organization organization = (Organization) cmbOrganizationType.getSelectedItem();
        if (organization != null){
            populateTable(organization);
        }
    }//GEN-LAST:event_cmbOrganizationTypeActionPerformed

    private void enterpriseNameTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_enterpriseNameTextFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_enterpriseNameTextFieldFocusGained

    private void enterpriseNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enterpriseNameTextFieldActionPerformed

    private void cmbOrganizationTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbOrganizationTypeMouseClicked
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_cmbOrganizationTypeMouseClicked

    private void cmbOrganizationTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbOrganizationTypeItemStateChanged
        // TODO add your handling code here:
         Organization organization = (Organization) cmbOrganizationType.getSelectedItem();
        cmbOrganizationName.removeAllItems();
        cmbOrganizationName.addItem(organization.getRealName());
        
    }//GEN-LAST:event_cmbOrganizationTypeItemStateChanged

    private void tblOrganizationInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tblOrganizationInputMethodTextChanged
//        int selectedRow = organizationJTable.getSelectedRow();
//        Organization organization = (Organization) organizationJTable.getSelectedRow();
//        organization.getEmployeeDirectory().createEmployee(name);
//        uidTextField.setText( String.valueOf(tblPatient.getValueAt(selectedRow, 0)));
    }//GEN-LAST:event_tblOrganizationInputMethodTextChanged

    private void btnCreateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateEmployeeActionPerformed
        String check1 = "";
        Organization organization = (Organization) cmbOrganizationType.getSelectedItem();
        
        if (cmbOrganizationType.getSelectedItem().equals(null) )
        {
            cmbOrganizationType.setBorder(BorderFactory.createLineBorder(Color.RED));
            cmbOrganizationType.setForeground(Color.red);
            JOptionPane.showMessageDialog(null, 
                    new JLabel("<html><b>Select an Organization Type!</b></html>"), 
                    "Warning", JOptionPane.WARNING_MESSAGE);
            check1 = "return";
        }
        
        else if (cmbOrganizationName.getSelectedItem().equals(null) )
        {
           cmbOrganizationName.setBorder(BorderFactory.createLineBorder(Color.RED));
            cmbOrganizationName.setForeground(Color.red);
             JOptionPane.showMessageDialog(null, 
                     new JLabel("<html><b>Select an Organization Name!</b></html>"), 
                     "Warning", JOptionPane.WARNING_MESSAGE);
            check1 = "return";
        }
        else if (txtNameOfEmployee.getText().isEmpty()) {
           txtNameOfEmployee.setBorder(BorderFactory.createLineBorder(Color.RED));
            txtNameOfEmployee.setForeground(Color.red);
             JOptionPane.showMessageDialog(null, 
                     new JLabel("<html><b>Employee Name can not be same!</b></html>"), 
                     "Warning", JOptionPane.WARNING_MESSAGE);
            //JOptionPane.showMessageDialog(null, "Employee name cannot be empty.");
            check1 = "return";
            return;
        }
        
        else{
        
            for (Employee employee : organization.getEmployeeDirectory().getEmployeeList()) {

            if (employee.getName().equals(txtNameOfEmployee.getText())) {
                JOptionPane.showMessageDialog(null, 
                        new JLabel("<html><b>Multiple employees can not have same name!</b></html>"), 
                        "Warning", JOptionPane.WARNING_MESSAGE);
                check1 = "return";
                return;
            }}
        }
        
        if(check1 == "")
        {
        
        String name = txtNameOfEmployee.getText();
        
        organization.getEmployeeDirectory().createEmployee(name);
        populateTable(organization);
        
        final ImageIcon icon = new ImageIcon("..\\src\\Images\\approved.png");
        JOptionPane.showMessageDialog(null, "New Employee Created!","Approved",JOptionPane.INFORMATION_MESSAGE,icon);
                   
        //JOptionPane.showMessageDialog(null, "Employee created successfully!");
        
        txtNameOfEmployee.setText("");
        //organizationJComboBox.removeItem(organizationJComboBox.getSelectedItem());
        //organizationEmpJComboBox.removeItem(organizationEmpJComboBox.getSelectedItem());
        dB4OUtil.storeSystem(system);
        }
    }//GEN-LAST:event_btnCreateEmployeeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateEmployee;
    private javax.swing.JComboBox cmbOrganizationName;
    private javax.swing.JComboBox cmbOrganizationType;
    private javax.swing.JTextField enterpriseNameTextField;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCreateEmployee;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblManageEmployee;
    private javax.swing.JLabel lblNameOfEmployee;
    private javax.swing.JLabel lblNameOfOrganization;
    private javax.swing.JLabel lblTypeOfOrganization;
    private javax.swing.JSeparator nameSeparator;
    private javax.swing.JSeparator nameSeparator1;
    private javax.swing.JSeparator nameSeparator3;
    private javax.swing.JSeparator nameSeparator4;
    private javax.swing.JTable tblOrganization;
    private javax.swing.JTextField txtEnterpriseName;
    private javax.swing.JTextField txtNameOfEmployee;
    // End of variables declaration//GEN-END:variables
}
