/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.LegalOfficerRole;

import Business.DB4OUtil.DB4OUtil;
import userinterface.SystemCoordinatorRole.*;
import Business.EcoSystem;
import userinterface.DoctorRole.*;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.Organization.LegalOfficerOrganization;
import Business.Organization.Organization;
import Magic.Design.*;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import static javax.swing.SwingUtilities.getWindowAncestor;

/**
 *

 * @author Nishita

 */
public class LegalOfficerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LegalOfficerWorkAreaJPanel
     */
    
    private UserAccount userAccount;
    boolean a = true;
    DoctorOrganization doctorOrganization;
    private LegalOfficerOrganization legalofficerorganization;
    private Enterprise enterprise;
    private EcoSystem system;
    private Network network;
    
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    public LegalOfficerWorkAreaJPanel(UserAccount account, LegalOfficerOrganization legalofficerorganization, Enterprise enterprise, EcoSystem business, Network network) {
        initComponents();
        this.system = system;
        this.userAccount = account;
        this.legalofficerorganization = legalofficerorganization;
        this.enterprise = enterprise;
        this.system = business;
        this.network = network;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);    
    }
    
    public void clickmenu(JPanel h1, JPanel h2, int numberbool){
        
        if(numberbool == 1){
            
            h1.setBackground(new Color(70,55,37));
            h2.setBackground(new Color(216,99,1));        
        }
        else{
            h1.setBackground(new Color(216,99,1));
            h2.setBackground(new Color(70,55,37));   
        }  
    }
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        btnProfile = new javax.swing.JLabel();
        btnManageRequests = new javax.swing.JLabel();
        btnConsent = new javax.swing.JLabel();
        userProcessContainer = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(800, 500));
        setLayout(new java.awt.BorderLayout());

        Header.setBackground(new java.awt.Color(102, 102, 102));
        Header.setPreferredSize(new java.awt.Dimension(800, 50));
        Header.setLayout(new java.awt.GridLayout(1, 0));

        btnProfile.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnProfile.setText("Profile");
        btnProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProfileMouseClicked(evt);
            }
        });
        Header.add(btnProfile);

        btnManageRequests.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnManageRequests.setForeground(new java.awt.Color(255, 255, 255));
        btnManageRequests.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnManageRequests.setText("Manage Requests");
        btnManageRequests.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageRequests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnManageRequestsMouseClicked(evt);
            }
        });
        Header.add(btnManageRequests);

        btnConsent.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnConsent.setForeground(new java.awt.Color(255, 255, 255));
        btnConsent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnConsent.setText("Check Acceptance Status");
        btnConsent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsentMouseClicked(evt);
            }
        });
        Header.add(btnConsent);

        add(Header, java.awt.BorderLayout.PAGE_START);

        userProcessContainer.setBackground(new java.awt.Color(255, 204, 204));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        add(userProcessContainer, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsentMouseClicked
        // TODO add your handling code here:
        PatientConsentJPanel patientConsentJPanel = new PatientConsentJPanel(system, userAccount, network);
        userProcessContainer.add("PatientConsentJPanel",patientConsentJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnConsentMouseClicked

    private void btnManageRequestsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageRequestsMouseClicked
        // TODO add your handling code here:
        ManageLegalOfficerRequestJPanel manageLegalOfficerRequest = new ManageLegalOfficerRequestJPanel(system, userAccount, legalofficerorganization, enterprise);
        userProcessContainer.add("ManageLegalOfficerRequestJPanel",manageLegalOfficerRequest);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageRequestsMouseClicked

    private void btnProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProfileMouseClicked
        // TODO add your handling code here:
        ManageLegalOfficerProfile manageLegalOfficerProfile = new ManageLegalOfficerProfile(userAccount,legalofficerorganization,enterprise);
        userProcessContainer.add("ManageLegalOfficerProfile",manageLegalOfficerProfile);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnProfileMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JLabel btnConsent;
    private javax.swing.JLabel btnManageRequests;
    private javax.swing.JLabel btnProfile;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
