/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package userinterface.LegalOfficerRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.Bone_Marrow_Bank_Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import Magic.Design.*;
import Magic.Design.MyJLabel;
import Magic.Design.MyTableFormat;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URL;
import java.util.Properties;
import javax.imageio.ImageIO;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *

 * @author Nishita

 */
public class PatientConsentJPanel extends javax.swing.JPanel {

    /** Creates new form PatientConsentJPanel */
    private EcoSystem system;
    private UserAccount userAccount;
    private Network network;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    public PatientConsentJPanel(EcoSystem system, UserAccount userAccount, Network network) {
        initComponents();
        this.system = system;
        this.userAccount = userAccount;
        this.network = network;
        tblPatientConsent.getTableHeader().setDefaultRenderer(new MyTableFormat());
        populatePatientConsentTable();
    }

    

    public void populatePatientConsentTable(){
        DefaultTableModel model = (DefaultTableModel)tblPatientConsent.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[5];
            row[0] = request;
            row[1] = request.getPatient();
            row[2] = request.getPatient().getName();
           // row[3] = request.getPatient().getContact();
            row[3] = request.getPatient().getEmailID();
            row[4] = request.getStatus();
             
            model.addRow(row);
        }
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatientConsent = new javax.swing.JTable();
        btnSignForm = new javax.swing.JButton();
        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();
        btnDisplayConsentForm = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblTreatmentConsentLetterStatus = new javax.swing.JLabel();
        lblConsent = new javax.swing.JLabel();
        btnPatientAgreement = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPatientConsent.setBackground(new java.awt.Color(153, 153, 153));
        tblPatientConsent.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        tblPatientConsent.setForeground(new java.awt.Color(255, 255, 255));
        tblPatientConsent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Number", "Patient ID", "Patient Name", "Patient email", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPatientConsent.setFocusable(false);
        tblPatientConsent.setGridColor(new java.awt.Color(0, 0, 0));
        tblPatientConsent.setRowHeight(30);
        jScrollPane1.setViewportView(tblPatientConsent);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 1150, 190));

        btnSignForm.setBackground(new java.awt.Color(102, 102, 102));
        btnSignForm.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSignForm.setForeground(new java.awt.Color(255, 255, 255));
        btnSignForm.setText("Sign the form");
        btnSignForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignFormActionPerformed(evt);
            }
        });
        add(btnSignForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 130, 40));

        btnApprove.setBackground(new java.awt.Color(102, 102, 102));
        btnApprove.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnApprove.setForeground(new java.awt.Color(255, 255, 255));
        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });
        add(btnApprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 620, 90, 40));

        btnReject.setBackground(new java.awt.Color(102, 102, 102));
        btnReject.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnReject.setForeground(new java.awt.Color(255, 255, 255));
        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });
        add(btnReject, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 620, 80, 40));

        btnDisplayConsentForm.setBackground(new java.awt.Color(102, 102, 102));
        btnDisplayConsentForm.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnDisplayConsentForm.setForeground(new java.awt.Color(255, 255, 255));
        btnDisplayConsentForm.setText("Display Consent Form");
        btnDisplayConsentForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayConsentFormActionPerformed(evt);
            }
        });
        add(btnDisplayConsentForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 180, 40));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(926, 70));

        lblTreatmentConsentLetterStatus.setBackground(new java.awt.Color(102, 102, 102));
        lblTreatmentConsentLetterStatus.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTreatmentConsentLetterStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblTreatmentConsentLetterStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTreatmentConsentLetterStatus.setText("Treatment Consent Letter Status");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblTreatmentConsentLetterStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 1363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTreatmentConsentLetterStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1590, -1));

        lblConsent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 164, 0)));
        add(lblConsent, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 410, 180, 180));

        btnPatientAgreement.setBackground(new java.awt.Color(102, 102, 102));
        btnPatientAgreement.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnPatientAgreement.setForeground(new java.awt.Color(255, 255, 255));
        btnPatientAgreement.setText("Patient Agreement");
        btnPatientAgreement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientAgreementActionPerformed(evt);
            }
        });
        add(btnPatientAgreement, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 160, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblPatientConsent.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, new JLabel(  "<html><b>Please select a row from the table</b></html>"), "Warning", JOptionPane.WARNING_MESSAGE);
           
           // JOptionPane.showMessageDialog(null,"Please select a row", "Info", JOptionPane.INFORMATION_MESSAGE);
            
            return;
        }
        else{
        WorkRequest request = (WorkRequest)tblPatientConsent.getValueAt(selectedRow, 0);
      
        request.setStatus("Legally Approved. Passing to BoneMarrowBank");
        //request.setUserAccount(userAccount);
        //userAccount.getWorkQueue().getWorkRequestList().add(request);
        dB4OUtil.storeSystem(system);
        populatePatientConsentTable();
        
        //JOptionPane.showMessageDialog(null,"Legally Approved Successfully", "Info", JOptionPane.INFORMATION_MESSAGE);
        JOptionPane.showMessageDialog(null, new JLabel(  "<html><b>Legally approved successfully!</b></html>"),"Info", JOptionPane.INFORMATION_MESSAGE);
           
        
        Enterprise ent = null;
        Organization org = null;
        
        for (Enterprise enterprise : network.getEnterprise_Directory().getEnterpriseList()) {
            if (enterprise.getEnterpriseType().toString().equals("BoneMarrowBank")) {
            
                ent = enterprise;
                System.out.println(enterprise);
                break;
            }
        }
        
        for (Organization organization : ent.getOrganizationDirectory().getOrganizationList()) {
            if(organization instanceof Bone_Marrow_Bank_Organization) {
                org = organization;
                break;
            }
        }
        
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(request);
            System.out.println(org.getName()+"Orgcheck");    
        } else {
         JOptionPane.showMessageDialog(null, "No organization present", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        UserAccount userAc = null;
        for (UserAccount userAcc: org.getUserAccountDirectory().getUserAccountList()){
            userAc = userAcc;
            userAc.getWorkQueue().getWorkRequestList().add(request);
            break;
        }
        }
        
       
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnSignFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignFormActionPerformed
        // TODO add your handling code here:
        BufferedImage img1 = null;
        try {
//            URI urlToImage = this.getClass().getResource("/organ_Agreement_DonorReceiverAdvocate.png");
                img1 = ImageIO.read(new File("C:\\Users\\HP\\Downloads\\AED_FinalProject-main\\Aed_final_v4\\src\\organ_Agreement_DonorReceiverAdvocate.jpg"));

//img1 = ImageIO.read(new File("C:/Users/HP/Downloads/AED_FinalProject-main/Aed final v4/src/userinterface/LegalOfficerRole/organ_Agreement_DonorReceiverAdvocate.png"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        Image dimg = img1.getScaledInstance(lblConsent.getWidth(), lblConsent.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimg);
        lblConsent.setIcon(imageIcon);
        
        
        
        
    }//GEN-LAST:event_btnSignFormActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblPatientConsent.getSelectedRow();
        
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, new JLabel(  "<html><b>Please select a row from the table</b></html>"), "Warning", JOptionPane.WARNING_MESSAGE);
           
           // JOptionPane.showMessageDialog(null,"Please select a row", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        else{
        WorkRequest request = (WorkRequest)tblPatientConsent.getValueAt(selectedRow, 0);
      
        request.setStatus("Legally Disapproved");
        request.setUserAccount(userAccount);
        userAccount.getWorkQueue().getWorkRequestList().add(request);
       
        dB4OUtil.storeSystem(system);
        populatePatientConsentTable();
        JOptionPane.showMessageDialog(null, new JLabel("<html><b> Legally Disapproved!</b></html>"), "Info", JOptionPane.INFORMATION_MESSAGE);
           
        //JOptionPane.showMessageDialog(null,"Legally Disapproved", "Info", JOptionPane.INFORMATION_MESSAGE);
        
        }
        
    }//GEN-LAST:event_btnRejectActionPerformed

    private void btnPatientAgreementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientAgreementActionPerformed
        // TODO add your handling code here:
        BufferedImage img1 = null;
        try {
            img1 = ImageIO.read(new File("C:\\Users\\HP\\Downloads\\AED_FinalProject-main\\Aed_final_v4\\src\\organ_Agreement_Donor.jpg"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        Image dimg = img1.getScaledInstance(lblConsent.getWidth(), lblConsent.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimg);
        lblConsent.setIcon(imageIcon);

    }//GEN-LAST:event_btnPatientAgreementActionPerformed

    private void btnDisplayConsentFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayConsentFormActionPerformed
        // TODO add your handling code here:
        BufferedImage img1 = null;
        try {
            img1 = ImageIO.read(new File("C:\\Users\\HP\\Downloads\\AED_FinalProject-main\\Aed_final_v4\\src\\organ_Agreement.jpg"));
        } catch (IOException e) {
            e.printStackTrace();
        }
        Image dimg = img1.getScaledInstance(lblConsent.getWidth(), lblConsent.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimg);
        lblConsent.setIcon(imageIcon);

    }//GEN-LAST:event_btnDisplayConsentFormActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnDisplayConsentForm;
    private javax.swing.JButton btnPatientAgreement;
    private javax.swing.JButton btnReject;
    private javax.swing.JButton btnSignForm;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblConsent;
    private javax.swing.JLabel lblTreatmentConsentLetterStatus;
    private javax.swing.JTable tblPatientConsent;
    // End of variables declaration//GEN-END:variables

}
