/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.GovernmentCoordinatorRole;

/**
 *
 * @author Nishita
 */

import Business.DB4OUtil.DB4OUtil;
import userinterface.LegalOfficerRole.*;
import userinterface.SystemCoordinatorRole.*;
import Business.EcoSystem;
import userinterface.DoctorRole.*;
import Magic.Design.*;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.Organization.GovernmentOrganization;
import Business.Organization.Organization;
import Business.People.DonorDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.io.IOException;
import java.security.GeneralSecurityException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import static javax.swing.SwingUtilities.getWindowAncestor;


public class GovernmentCoordinatorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GovernmentCoordinatorWorkAreaJPanel
     */
    
    private UserAccount userAccount;
    private GovernmentOrganization govtorganization;
    boolean a = true;
    DoctorOrganization doctorOrganization;
    private Enterprise enterprise;
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public GovernmentCoordinatorWorkAreaJPanel(UserAccount account, GovernmentOrganization govtorganization, Enterprise enterprise, EcoSystem business, Network network) {
        initComponents();
        this.system = system;
        this.userAccount = account;
        this.govtorganization = govtorganization;
        this.enterprise = enterprise;
        this.system = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    public void changecolor(JPanel hover, Color rand){
        hover.setBackground(rand);    
    }
    
    public void clickmenu(JPanel h1, JPanel h2, int numberbool){
        
        if(numberbool == 1){
            
            h1.setBackground(new Color(70,55,37));
            h2.setBackground(new Color(216,99,1));        
        }
        else{
            h1.setBackground(new Color(216,99,1));
            h2.setBackground(new Color(70,55,37));   
        }  
    }
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        BtnSelfProfile = new javax.swing.JLabel();
        BtnDonorStatus = new javax.swing.JLabel();
        BtnDonorRequests = new javax.swing.JLabel();
        userProcessContainer = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 204, 204));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setLayout(new java.awt.BorderLayout());

        Header.setBackground(new java.awt.Color(102, 102, 102));
        Header.setPreferredSize(new java.awt.Dimension(800, 50));
        Header.setLayout(new java.awt.GridLayout(1, 0));

        BtnSelfProfile.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BtnSelfProfile.setForeground(new java.awt.Color(255, 255, 255));
        BtnSelfProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnSelfProfile.setText("Edit Self Profile");
        BtnSelfProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnSelfProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSelfProfileMouseClicked(evt);
            }
        });
        Header.add(BtnSelfProfile);

        BtnDonorStatus.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BtnDonorStatus.setForeground(new java.awt.Color(255, 255, 255));
        BtnDonorStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnDonorStatus.setText("Check Donor Status");
        BtnDonorStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnDonorStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnDonorStatusMouseClicked(evt);
            }
        });
        Header.add(BtnDonorStatus);

        BtnDonorRequests.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BtnDonorRequests.setForeground(new java.awt.Color(255, 255, 255));
        BtnDonorRequests.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtnDonorRequests.setText("Volunteer Donor Requests");
        BtnDonorRequests.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnDonorRequests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnDonorRequestsMouseClicked(evt);
            }
        });
        Header.add(BtnDonorRequests);

        add(Header, java.awt.BorderLayout.PAGE_START);

        userProcessContainer.setBackground(new java.awt.Color(255, 204, 204));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        add(userProcessContainer, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSelfProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSelfProfileMouseClicked
        // TODO add your handling code here:
        ManageGovernmentCoordinatorProfile manageGovtCoordinatorProfile = new ManageGovernmentCoordinatorProfile(userAccount,govtorganization,enterprise);
        userProcessContainer.add("ManageGovernmentCoordinatorProfile",manageGovtCoordinatorProfile);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_BtnSelfProfileMouseClicked

    private void BtnDonorStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDonorStatusMouseClicked
        // TODO add your handling code here:
        
        DonorStatusJPanel Profile = new DonorStatusJPanel(system);
        userProcessContainer.add("DonorStatusJPanel", Profile);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_BtnDonorStatusMouseClicked

    private void BtnDonorRequestsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDonorRequestsMouseClicked
        // TODO add your handling code here:
        
        VolunteerDonorRequestJPanel Profile = new VolunteerDonorRequestJPanel(system);
        userProcessContainer.add("VolunteerDonorRequestJPanel", Profile);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_BtnDonorRequestsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtnDonorRequests;
    private javax.swing.JLabel BtnDonorStatus;
    private javax.swing.JLabel BtnSelfProfile;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
